//> using dep org.soundsofscala::sounds-of-scala::0.1.0
//> using dep org.http4s::http4s-dom::0.2.11
//> using dep com.armanbilge::calico::0.2.3
//> using dep dev.optics::monocle-core::3.3.0
//> using dep org.typelevel::kittens::3.4.0
//> using dep io.circe::circe-core::0.14.10
//> using dep io.circe::circe-scalajs::0.14.10
//> using dep io.circe::circe-parser::0.14.10
//> using dep org.typelevel::keypool::0.4.10
//> using platform js
//> using jsModuleKind common
//> using option -no-indent
//> using option -deprecation
//> using option -Wunused:all
//> using option -Xkind-projector
//> using publish.repository ivy2local
//> using publish.organization com.kubukoz
//> using publish.name calico-fun-frontend
//> using publish.version 0.1.0-SNAPSHOT
